[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Manual Lab"
authors = [{name = "Ahmed Reda", email = "ahmed.reda@efabless.com"}]
dynamic = ["version", "description"]
